parameters:  
  "service-dir":
    default: "sdk/schemaregistry"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/../data-plane/Microsoft.EventHub/stable/2022-10"
    output-file: "SchemaRegistry.json"
    examples-directory: "examples"
  "@azure-tools/typespec-python":    
    package-dir: "azure-schemaregistry"
    package-name: "{package-dir}"  
    package-mode: dataplane
    package-version: 1.3.0b3
    emitter-output-dir: "{project-root}/{service-dir}/{package-name}"

