parameters:  
  "service-dir":
    default: "sdk/appconfiguration"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/Microsoft.AppConfiguration/{version-status}/{version}/appconfiguration.json"
  "@azure-tools/typespec-python":    
    package-dir: "azure-appconfiguration-provider"
    package-name: "{package-dir}"  
    package-mode: dataplane
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.Data.AppConfiguration"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "azure-appconfiguration-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/azure-appconfiguration-rest"
      description: "Azure App Configuration"
  "@azure-tools/typespec-java":
    package-dir: "azure-data-appconfiguration"
    namespace: com.azure.data.appconfiguration
linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"
